apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 67.5.0
    chart: kube-prometheus-stack
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

