apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
spec:
  destination:
    name: ''
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: examples/standard
    repoURL: https://github.com/kubernetes/kube-state-metrics.git
    targetRevision: HEAD
    kustomize:
      namespace: kube-system
  sources: []
  project: default
