apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
data:
  config.yml: |
    bootstrapDns:
      - upstream: 103.86.96.100
      - upstream: 103.86.99.100
    upstreams:
      groups:
        default:
          - 103.86.96.100
          - 103.86.99.100
    conditional:
      fallbackUpstream: false
      mapping:
        luke-domain.com: 172.16.20.254
    ports:
      dns: 53
      http: 4000
    blocking:
      denylists:
        ads:
          - https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/wildcard/ultimate.txt
        security:
          - https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/wildcard/tif.txt
      allowlists:
        ads:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/share/facebook.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/share/microsoft.txt
      clientGroupsBlock:
        default:
          - ads
          - security
    redis:
      address: blocky-cache:6379
      connectionAttempts: 10
      connectionCooldown: 3s
    prometheus:
      enable: true
      path: /metrics
    queryLog:
      type: postgresql
      target: 'postgres://blocky@blocky-log-db:5432/blocky'
      logRetentionDays: 7
