apiVersion: v1
kind: Service
metadata:
  name: blocky
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
spec:
  selector:
    name: blocky
  type: NodePort
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      name: web
    - port: 53
      protocol: TCP
      targetPort: 53
      name: dns-tcp
    - port: 53
      protocol: UDP
      targetPort: 53
      name: dns-udp
