apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: argocd
spec:
  destination:
    namespace: blocky
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/blocky/overlays/prod
    repoURL: https://github.com/sl4te-sm/luke-infrastructure.git
    targetRevision: v1.2.1
  syncPolicy:
    automated:
      selfHeal: true
