apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: argocd
spec:
  destination:
    namespace: blocky
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/blocky/overlays/prod
    repoURL: https://gitlab.com/grayskull757/proxmox-cluster.git
    targetRevision: 1.1.0
  syncPolicy:
    automated:
      selfHeal: true
