apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: true
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
