apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: inteldeviceplugins-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.31.1
    chart: intel-device-plugins-operator
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-gpu
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: inteldeviceplugins-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.31.1
    chart: intel-device-plugins-gpu
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
