apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-operator
  namespace: argocd
spec:
  destination:
    namespace: dragonfly-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/dragonflydb/dragonfly-operator.git
    targetRevision: v1.1.11
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
