apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/homeassistant
    repoURL: https://gitlab.com/grayskull757/proxmox-cluster.git
    targetRevision: v1.3.0
