apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: inteldeviceplugins-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: intel-device-plugins-operator
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.32.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
  sources: []
