apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    chart: nfs-subdir-external-provisioner
    helm:
      parameters:
        - name: nfs.server
          value: 172.16.20.14
        - name: nfs.path
          value: /home/luke-kubecluster
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
