apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openebs
    pod-security.kubernetes.io/enforce: privileged
  name: openebs
spec:
  finalizers:
  - kubernetes

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: openebs
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.3.2
    chart: openebs
    helm:
      valuesObject:
        mayastor:
          csi:
            node:
              initContainers:
                enabled: false
        engines:
          local:
            lvm:
              enabled: false
            zfs:
              enabled: false
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-triple-replica
parameters:
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
allowVolumeExpansion: true

---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: luke-kubetop-1-pool
  namespace: openebs
spec:
  node: luke-kubetop-1
  disks:
    - uring:///dev/vdb
  topology:
    labelled:
      topology-key: topology-value

---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: luke-kubetop-2-pool
  namespace: openebs
spec:
  node: luke-kubetop-2
  disks:
    - uring:///dev/vdb
  topology:
    labelled:
      topology-key: topology-value

---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: luke-kubetop-3-pool
  namespace: openebs
spec:
  node: luke-kubetop-3
  disks:
    - uring:///dev/vdb
  topology:
    labelled:
      topology-key: topology-value
