apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`homebridge.services.luke-domain.com`)
      priority: 10
      services:
        - name: homebridge
          port: 80
