apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      containers:
      - name: homebridge
        image: homebridge/homebridge:latest
        volumeMounts:
        - name: homebridge-data
          mountPath: /homebridge
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - curl --fail localhost:8581 || exit 1
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 2
          failureThreshold: 5
        ports:
          - containerPort: 8581
            protocol: TCP
            name: homebridge-ui
          - containerPort: 51465
            protocol: TCP
            name: homebridge-mdns
        env:
          - name: HOMEBRIDGE_CONFIG_UI
            value: "1"
          - name: HOMEBRIDGE_CONFIG_UI_PORT
            value: "8581"
          - name: TZ
            value: "America/Chicago"
      volumes:
      - name: homebridge-data
        persistentVolumeClaim:
          claimName: homebridge-pvc
      hostNetwork: true
