apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  source:
    path: deploy
    repoURL: 'https://github.com/rancher/local-path-provisioner'
    targetRevision: v0.0.31
    kustomize:
      patches:
        - patch: |-
            kind: ConfigMap
            apiVersion: v1
            metadata:
              name: local-path-config
              namespace: local-path-storage
            data:
              config.json: |-
                {
                        "nodePathMap":[
                        {
                                "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                                "paths":["/var/local-path-provisioner"]
                        }
                        ]
                }
        - patch: |-
            apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: local-path
              annotations:
                storageclass.kubernetes.io/is-default-class: "false"
        - patch: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: local-path-storage
              labels:
                pod-security.kubernetes.io/enforce: privileged
  destination:
    namespace: local-path-storage
    server: 'https://kubernetes.default.svc'
