apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    name: ''
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://traefik.github.io/charts
    targetRevision: 33.0.0
    chart: traefik
    helm:
      parameters:
        - name: deployment.kind
          value: DaemonSet
        - name: service.type
          value: NodePort
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
