apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: dashboard
      name: dashboard
      protocol: TCP
    - port: 80
      targetPort: web
      name: web
      protocol: TCP
    - port: 443
      targetPort: websecure
      name: websecure
      protocol: TCP
  selector:
    app: traefik
