- name: Install etcd hosts
  hosts: databases
  become: true
  tasks:
    - name: Install tar
      ansible.builtin.dnf:
        name: tar
        state: latest

    - name: Install etcd
      script: /home/luke/ansible/scripts/install_etcd.sh

    - name: Open firewall ports
      ansible.posix.firewalld:
        port: 2379-2380/tcp
        permanent: true
        state: enabled

    - name: Create etcd group
      ansible.builtin.group:
        name: etcd
        state: present

    - name: Create etcd user
      ansible.builtin.user:
        name: etcd
        group: etcd
        shell: /sbin/nologin
        system: true

    - name: Create etcd data directory
      ansible.builtin.file:
        path: /var/lib/etcd
        state: directory
        owner: etcd
        group: etcd
        mode: '0775'

    - name: Configure SELinux policy for etcd
      script: /home/luke/ansible/scripts/etcd_selinux.sh

    - name: Setup systemd service
      script: /home/luke/ansible/scripts/etcd_systemd.sh

- name: Deploy etcd certificates
  hosts: localhost
  become: true
  tasks:
    - name: Deploy certs
      script: /home/luke/ansible/scripts/etcd_certs.sh

      #- name: Start the etcd service
      #hosts: databases
      #become: true
      #tasks:
      #- name: start service
      #ansible.builtin.systemd_service:
      #  name: etcd
      #  state: started
      #  enabled: true
