- name: Configure etcd hosts
  hosts: databases
  become: true
  tasks:
    - name: Set environment variables
      environment:
        ETCD_INITIAL_CLUSTER: etcd1=https://172.16.22.10:2380,etcd2=https://172.16.22.11:2380,etcd3=https://172.16.22.12:2380
        ETCD_INITIAL_CLUSTER_STATE: new
        ETCD_INITIAL_CLUSTER_TOKEN: luke-etcdcluster
        ETCD_CLIENT_CRL_FILE: /mnt/servershare/intermediate.crl.pem
        ETCD_TRUSTED_CA_FILE: /home/luke/.ssl/ca.crt
        ETCD_PEER_CRL_FILE: /mnt/servershare/intermediate.crl.pem
        ETCD_PEER_TRUSTED_CA_FILE: /home/luke/.ssl/ca.crt

    - name: Enable firewall ports
      ansible.posix.firewalld:
        port: 2379-2380/tcp
        permanent: true
        state: enabled
