- name: Install etcd hosts
  hosts: databases
  become: true
  tasks:
    - name: Install tar
      ansible.builtin.dnf:
        name: tar
        state: latest

    - name: Install etcd
      script: /home/luke/ansible/scripts/install_etcd.sh

    - name: Configure firewall ports
      ansible.posix.firewalld:
        port: 2379-2380/tcp
        permanent: true
        state: enabled

    - name: Configure etcd group
      ansible.builtin.group:
        name: etcd
        state: present

    - name: Configure etcd user
      ansible.builtin.user:
        name: etcd
        group: etcd
        shell: /sbin/nologin
        system: true

    - name: Configure etcd systemd service
      ansible.builtin.file:
        path: /var/lib/etcd
        state: directory
        owner: etcd
        group: etcd
        mode: '0775'

    - name: Configure SELinux policy for etcd
      script: /home/luke/ansible/scripts/etcd_selinux.sh
