- name: Install etcd hosts
  hosts: databases
  become: true
  tasks:
    - name: Install tar
      ansible.builtin.dnf:
        name: tar
        state: latest

    - name: Install etcd
      script: /home/luke/ansible/scripts/install_etcd.sh

    - name: Configure firewall ports
      ansible.posix.firewalld:
        port: 2379-2380/tcp
        permanent: true
        state: enabled
