- name: Setup K3s worker nodes
  hosts: k3controlnodes
  become: true
  tasks:
    - name: Enable apiserver port
      ansible.posix.firewalld:
        port: 6443/tcp
        permanent: true
        state: enabled

    - name: Enable Flannel VXLAN port
      ansible.posix.firewalld:
        port: 8472/udp
        permanent: true
        state: enabled

    - name: Enable Kubelet metrics port
      ansible.posix.firewalld:
        port: 10250/tcp
        permanent: true
        state: enabled

    - name: Add pods to trusted zone
      ansible.posix.firewalld:
        zone: trusted
        source: 10.42.0.0/16
        permanent: true
        state: enabled

    - name: Add services to trusted zone
      ansible.posix.firewalld:
        zone: trusted
        source: 10.43.0.0/16
        permanent: true
        state: enabled
    
    - name: Install k3s server node
      script: /home/luke/ansible/scripts/k3s_config.sh
