- name: Setup kubernetes control nodes
  hosts: k8controlnodes
  become: true
  tasks:
    - name: Enable IPv4 packet forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.d/k8s.conf
        sysctl_set: true
        state: present
        reload: true

    - name: Open control plane ports
      ansible.posix.firewalld:
        ports:
          - 6443/tcp
          - 2379-2380/tcp
          - 10250/tcp
          - 10259/tcp
          - 10257/tcp
        permanent: true
        state: enabled

    - name: Install prerequisite software
      ansible.builtin.dnf:
        name:
          - tar
          - wget
        state: latest

    - name: Install containerd
      script: /home/luke/ansible/scripts/install_containerd.sh
