apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dns
  - ../../base/cache
  - ../../base/database
commonLabels:
  app.kubernetes.io/part-of: blocky-dns-dev
  app.kubernetes.io/managed-by: argocd
nameSuffix: -dev
images:
  - name: redis
    newTag: latest
  - name: postgres
    newTag: "14"
  - name: blocky
    newTag: latest
