apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-a-records-conf
data:
  a-records.conf: | 
    server: 
      private-domain: "luke-domain.com"
      domain-insecure: "luke-domain.com"
      local-zone: "luke-domain.com" transparent
      local-data: "miniswitch.luke-domain.com IN A 172.16.10.1"
      local-data: "bigswitch.luke-domain.com IN A 172.16.10.2"
      local-data: "familyroomap.luke-domain.com IN A 172.16.10.3"
      local-data: "bedroomap.luke-domain.com IN A 172.16.10.4"
      local-data: "libraryap.luke-domain.com IN A 172.16.10.5"
      local-data: "officeap.luke-domain.com IN A 172.16.10.6"
      local-data: "luke-vmtop-1.luke-domain.com IN A 172.16.20.10"
      local-data: "luke-vmtop-2.luke-domain.com IN A 172.16.20.11"
      local-data: "luke-vmtop-3.luke-domain.com IN A 172.16.20.12"
      local-data: "luke-nastop.luke-domain.com IN A 172.16.20.13"
      local-data: "files.luke-domain.com IN A 172.16.20.14"
      local-data: "luke-housetop.luke-domain.com IN A 172.16.30.148"
      local-data: "firewall.luke-domain.com IN A 172.16.30.254"
      local-data: "mortonprinter.luke-domain.com IN A 172.16.40.28"
      local-data: "luke-fliptop.luke-domain.com IN A 172.16.30.163"
      local-data: "luke-proxytop-1.luke-domain.com IN A 172.16.20.40"
      local-data: "luke-proxytop-2.luke-domain.com IN A 172.16.20.41"
      local-data: "luke-controltop-1.luke-domain.com IN A 172.16.20.20"
      local-data: "luke-controltop-2.luke-domain.com IN A 172.16.20.21"
      local-data: "luke-controltop-3.luke-domain.com IN A 172.16.20.22"
      local-data: "luke-kubetop-1.luke-domain.com IN A 172.16.20.30"
      local-data: "luke-kubetop-2.luke-domain.com IN A 172.16.20.31"
      local-data: "luke-kubetop-3.luke-domain.com IN A 172.16.20.32"
      local-zone: "services.luke-domain.com." redirect
      local-data: "services.luke-domain.com. 86400 IN A 172.16.20.42"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-forward-zone-conf
data:
  forward-zone.conf: |
    forward-zone:
      name: "."
      forward-addr: 103.86.96.100
      forward-addr: 103.86.99.100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      name: unbound
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: unbound
    spec:
      containers:
        - image: klutchell/unbound
          imagePullPolicy: IfNotPresent
          name: unbound
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: unbound-forward-zone-volume
              mountPath: /etc/unbound/custom.conf.d/forward-zone.conf
              subPath: forward-zone.conf
            - name: unbound-a-records-volume
              mountPath: /etc/unbound/custom.conf.d/a-records.conf
              subPath: a-records.conf
      restartPolicy: Always
      volumes:
        - name: unbound-forward-zone-volume
          configMap:
            name: unbound-forward-zone-conf
        - name: unbound-a-records-volume
          configMap:
            name: unbound-a-records-conf
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  type: NodePort
  selector:
    name: unbound
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
