apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s-deployment.yaml
  - k8s-service.yaml
commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/instance: postgres-blocky-dns
  app.kubernetes.io/version: 17.4-alpine3.21
  app.kubernetes.io/component: database
