apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  labels:
    app: pve-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter
          ports:
            - containerPort: 9221
          envFrom:
            - secretRef:
                name: pve-creds
      
---
apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9221'
spec:
  selector:
    app: pve-exporter
  ports:
    - port: 9221
      targetPort: 9221
